# Generated by Django 5.1.2 on 2024-10-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time',
            field=models.TimeField(max_length=30, verbose_name='Время выполнения привычки'),
        ),
    ]
